### ISSUE TITLE
[Feature Request] Would there be a grasscutter client ?

### ISSUE THREAD

**Issue by yw662** [Melledy/Grasscutter#1132]
**Is your feature request related to a problem? Please describe.**

Yeah I know what this project is/was *originally* for. But, would there be an grasscutter client, which, at least, can be an open source alternative to the original game ?

**Describe the solution you'd like**

Let's have a game client for the grasscutter game.

**Describe alternatives you've considered**

The alternative you are currently using.

**Additional context**

**Comment by Birdulon** [comment]
This topic has been discussed a few times, an open source recreation of the AnimeGame client is a significant undertaking that would also ironically have no need for GrassCutter servers since the majority of players are only interested in gameplay that can be achieved entirely offline or with basic P2P multiplayer.
A few people have expressed personal interest in making such things but it's nothing to do with the Grasscutters team, outside of joke proposals like a decoy client that uses entirely original assets as proof that Grasscutter is a generic multiplayer game server that just happens to be compatible with a certain proprietary game when certain data is provided to it.
