### ISSUE TITLE
能否添加账户密码功能，而不是随便输入什么密码都可以登录[Feature Request] 

### ISSUE THREAD

**Issue by lniuua** [Melledy/Grasscutter#1411]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Momoko-Ayase** [comment]
If you only mean login just use https://github.com/Xtao-Labs/GCAuth-OAuth
But if you mean native login (builtin) it seems impossible now due to the difficulty of verifying the secret ( Seems that someone answered this previously )
单纯的登录可以用 https://github.com/Xtao-Labs/GCAuth-OAuth 代替
但是原生登录因为没法验证你提交的密码是否正确 所以不太方便实现（之前好像有dalao提到过，~~除非去mhy偷密钥~~）

**Comment by zxl-qq927489674** [comment]
我觉得不好，因为这是私服。是自由的，可以让人不用记住繁琐的密码

**Comment by Momoko-Ayase** [comment]
> 我觉得不好，因为这是私服。是自由的，可以让人不用记住繁琐的密码

但也有一些情况需要加验证，比如群组服或公开服（你也不想别人登你账号吧）
But you may need password authorization on group server or public server ( You may not want someone to log into your account )

**Comment by KiminaNatsuki** [comment]
https://github.com/Xtao-Labs/GCAuth-OAuth
https://github.com/KingRainbow44/SimpleAuth
