### ISSUE TITLE
Bug Report of ZhongLi's shield inoperatively when character using elemental burst  钟离护盾在角色使用元素爆发时不会生效

### ISSUE THREAD

**Issue by s121091** [Melledy/Grasscutter#1450]
Bug Report of ZhongLi's shield inoperatively when character using an elemental burst

钟离护盾在角色使用元素爆发时不会生效

![image](https://user-images.githubusercontent.com/56785635/177540795-c6ecc870-efd0-4978-8ef9-a1bc09bf78b9.png)
Grasscutter version: 1.2.2-dev-GIT_NOT_FOUND
Development branch is used which updated on 6th July
Grasscutter版本：1.2.2-dev-GIT_NOT_FOUND
使用Development分支，7月6号更新版

Document 附件: Recording录屏: 
https://savef-my.sharepoint.com/:v:/g/personal/s121091_savef_onmicrosoft_com/EV3_-PilFfdDvcZXptDDWFsBMVpZU--AjwTxtKVROzEBeg?e=1ebpkW
https://drive.google.com/file/d/1tRY5nhsSdJJi54ym_emuJjyZrZHnrwDS/view?usp=sharing
↑↑ Kaedehara Kazuha died while using an elemental burst  万叶在有钟离护盾的情况下释放元素爆发受伤而死

**Comment by xNissX233** [comment]
I think that the problem is a bug that prevents invincibility frames during Elemental Burst cast, with or without shield. In the official servers you could use EB to prevent your character from getting damage, but you can't in Grasscutter.

**Comment by s121091** [comment]
Yep, it's possible, but with older grasscutter, ZhongLi's shields will always effective whether the character uses elemental bursts or not

**Comment by xNissX233** [comment]
The thing is that probably solving the invulnerability bug would be the correct way of fixing ZhongLi's shield too, since the problem may be that shields are not expected to work during invulnerability frames anyways. Think about it, if shields work during EB, they would be weakened after getting hit by attacks while doing EB, and that's not supposed to happen, shields must have the same HP before and after EB because you have to be invulnerable when in the animation.
ZhongLi's shield works as expected, the problem is that you should not be vulnerable (neither your shield should be hit) while doing EB.

**Comment by s121091** [comment]
Oh, I see(๑•͈ᴗ•͈)

**Comment by KiminaNatsuki** [comment]
Ah, this is a known issues already.
