### ISSUE TITLE
[Feature Request] Update the wiki

### ISSUE THREAD

**Issue by AwayJob** [Melledy/Grasscutter#1718]
**Is your feature request related to a problem? Please describe.**

Nope

**Describe the solution you'd like**

Update the wiki. Added a lot of changes, specially in `Troubleshooting.md`.

https://github.com/AwayJob/grasscutter-wiki

Made a lot of changes to the wiki for the people, made with love <3 (no homo)

I didn't change the Home cuz I'm tired lol

**Comment by Gmskjunior** [comment]
Exit

Em sáb., 27 de ago. de 2022 13:15, AwayJob ***@***.***>
escreveu:

**Comment by 4Benj** [comment]
We're going to be moving away from using GitHub's built in wiki, and will move to our own wiki soon due to limitations as displayed here (can't PR to the wiki itself) and also multi-lingual support.

I'm not going to close this since it has yet to be done, and I've assigned myself and @KingRainbow44 to this since we'd be the ones implementing it.

Thank you for your contribution, this will definitely help 😄 
(Apart from the fact that you called me Benji instead of Benj, seriously where did that 'i' come from?? 😆)

**Comment by AwayJob** [comment]
> (Apart from the fact that you called me Benji instead of Benj, seriously where did that 'i' come from?? laughing)

Oh crap, you're right lmao. But for real, I thought your username is Benji lol. Anyway, looking forward to the new wiki.

**Comment by KingRainbow44** [comment]
this is being done on [Grasscutter-Docs](https://github.com/Grasscutters/Grasscutter-Docs)
