### ISSUE TITLE
[Bug] Account Deletion Doesn't Work

### ISSUE THREAD

**Issue by ghost** [Melledy/Grasscutter#1745]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

The account delete command does not work

**Which branch did you use?**

Release 1.3.0

**Screenshots**

**Additional context**

12:36:39 <INFO:Language> Loading cached TextMaps
12:36:40 <INFO:ResourceLoader> Loading resources...
12:36:41 <INFO:ResourceLoader> Finished loading resources.
12:36:42 <INFO:Tools> GM Handbooks generated!
12:36:42 <INFO:Grasscutter> Starting Grasscutter...
12:36:42 <INFO:Grasscutter> Game version: 3.0.0
12:36:42 <INFO:Grasscutter> Grasscutter version: 1.3.0-1555010
12:36:44 <INFO:HttpServer> [Dispatch] Dispatch server started at 127.0.0.1:1025
12:36:44 <INFO:GameServer> Grasscutter is FREE software. If you have paid for this, you may have been scammed. Homepage: https://github.com/Grasscutters/Grasscutter
12:36:44 <INFO:GameServer> Game Server started at 127.0.0.1:22102
12:36:44 <INFO:Grasscutter> Done! For help, type "help"
\> account delete derpy
12:36:51 <INFO:CommandHandler> Account deleted.
\> account create derpy
12:36:55 <INFO:CommandHandler> An account with this username and/or UID already exists.

**Comment by natsurepo** [comment]
The account delete command will output a false "Account deleted" because there is no checks after executing account deletion whether the account is still in the database or not. It's kinda weird because it only happened on me when I tried to delete a new account that I haven't logged into with. Else, account delete command will work. It's probably something to do with DatabaseHelper.java

**Comment by KingRainbow44** [comment]
this was fixed at some point, closing issue.
