### ISSUE TITLE
[Bug] 大世界的怪物位置、宝箱位置好像有问题

### ISSUE THREAD

**Issue by 909101** [Melledy/Grasscutter#1783]
**Did you look for other closed issues that have the same problem?**
目前没有人提

**Describe the bug**
在北风狼王下方的传送点遇到了纯水精灵Boss才意识到了这个问题，然后在大世界其他地方发现了同样的问题，比如数量明显太多的丘丘人，或者一群盗宝团和一群丘丘人在一起和谐共处的场景。

宝箱也是同样的问题。在确认是新创建的账号的情况下，有部分有怪物守护的宝箱没有显示。部分摆在大世界的宝箱也不在了。比如蒙德教堂顶上的华丽就消失了，而庆云顶的珍贵就在。（在开启大世界脚本的情况下）

**Which branch did you use?**
1.3.0的grasscutter jar
resource 用的是 https://github.com/tamilpp25/Grasscutter_Resources

**Additional context**
如果这BUG是由于我用的resource不对导致的，麻烦大佬指路一下正确的resource怎么拿到，感谢

**Comment by minhngoc25a** [comment]
DeepL Translate:

Title: There seems to be a problem with the location of monsters and treasure chests in the big world

Did you look for other closed issues that have the same problem?
No one has mentioned it yet

Describe the bug
I realized the problem when I encountered a pure water elf boss at the teleportation point below the North Wind Wolf King, and then found the same problem elsewhere in the big world, such as the apparently excessive number of chuchus, or the scene where a group of treasure thieves and a group of chuchus are living together in harmony.

The same problem with treasure chests. In the case of a confirmed newly created account, there are some treasure chests with monsters guarding them that are not shown. Some of the treasure chests placed in the big world are also not there. For example, the magnificent one at the top of Mond Church is gone, while the precious one at the top of Keun is there. (With the big world script on)

Which branch did you use?
The grasscutter jar for 1.3.0
resource used is https://github.com/tamilpp25/Grasscutter_Resources

Additional context
If this bug is caused by the wrong resource, could you please show me how to get the correct resource, thanks!

**Comment by awaae001** [comment]
现在的割草机不支持
我们还有很差的路要走
