### ISSUE TITLE
Relic properties are missing weights! Please check your ReliquaryMainPropExcelConfigData or ReliquaryAffixExcelConfigData files in your ExcelBinOutput folder.

### ISSUE THREAD

**Issue by Rainrain2007** [Melledy/Grasscutter#185]
![image](https://user-images.githubusercontent.com/69844315/164971449-23eeeb05-d228-456a-a640-a4f26631e682.png)

**Comment by Rainrain2007** [comment]
![image](https://user-images.githubusercontent.com/69844315/164971479-7096a22f-4696-4fc0-9b78-b9f89a9479e1.png)
errors,what should i do?

**Comment by Alan-Raddam** [comment]
It's clearly saying that the dispatch servers's target port, which is 443 by default, is already occupied. Check if you have another application running on port 443 because it's quite common for https service. Or you might have tried to execute this java application twice. Check if you have killed the previous one.

**Comment by Rainrain2007** [comment]
![image](https://user-images.githubusercontent.com/69844315/164972239-0f8059c1-8b53-46b8-9aa6-ce043e7e6f3e.png)
should i kill them?

**Comment by Rainrain2007** [comment]
> 

successfully solved , thank you!
