### ISSUE TITLE
[Bug] The data file is empty and cannot join the server

### ISSUE THREAD

**Issue by xiaozhu52055** [Melledy/Grasscutter#1912]
The data file is empty and cannot join the server
![QQ截图20221029194127](https://user-images.githubusercontent.com/81459974/198829481-20d7aabe-bb0e-497f-813d-c0e5b2e902f4.png)

**Comment by 4Benj** [comment]
On newer versions of grasscutter, the data folder no longer dumps everything it needs. Instead, it will look for the any files it needs in the data folder, but if it can’t find it then it will use the default data located inside the jar. In order to customise the data, copy the data files from GitHub, place them inside the data directory, and edit the files.
Your cannot join server issue is unrelated.

**Comment by xiaozhu52055** [comment]
What is the path to the data file?

**Comment by Birdulon** [comment]
> What is the path to the data file?

You can get them from the source folder ( https://github.com/Grasscutters/Grasscutter/tree/development/src/main/resources/defaults/data ) or you can open the `.jar` file as a `zip` archive.
