### ISSUE TITLE
cant start server

### ISSUE THREAD

**Issue by DeletedUser575703f6** [Melledy/Grasscutter#2030]
com.google.gson.JsonSyntaxException: java.io.IOException: Invalid DynamicFloat definition - BOOLEAN

**Comment by der3318** [comment]
`grasscutter-1.4.3.jar` does not fully support v3.4 yet. Use resources v3.3 instead of v3.4: https://git.crepe.moe/grasscutters/Grasscutter_Resources/-/blob/d3a5672a77180b7c74cb6c89422e0f6eed67a064/Grasscutter_Resources-3.3.zip

And re-do the second step of https://github.com/Grasscutters/Grasscutter#running:

* Re-create (i.e., delete if exists) a folder named `resources` in the directory where grasscutter.jar is located.
* Move the `BinOutput`, `ExcelBinOutput`, `Readables`, `Scripts`, `Subtitle`, `TextMap` folders (these can be found in the above downloaded zip) into the `resources/` directory.

**Comment by salazarm** [comment]
Hello, I'm trying to access the zip folder above. It says I need approval? Can you help with this? Thanks :)

**Comment by der3318** [comment]
> Hello, I'm trying to access the zip folder above. It says I need approval? Can you help with this? Thanks :)

The GitLab repo was probably taken down (again) due to DMCA request. Someone in discord forum should be able to support you.

Alternatively, you can refer to other's backup (e.g., https://github.com/aquawius/Grasscutter_Resources) by searching "Grasscutter Resources".

**Comment by thecutefinder** [comment]
You can find the working resources [here](https://gitlab.com/YuukiPS/GC-Resources).
