### ISSUE TITLE
[Bug] Cooking/Shop inventories are empty and wishes don't work

### ISSUE THREAD

**Issue by pbz134** [Melledy/Grasscutter#2407]
**Did you look for other closed issues that have the same problem?**
Yes

**Describe the bug**
When approaching any seller, their inventory is empty, thus buying their items is not possible.
Same goes for cooking pots, which are unusable due to the empty inventory.
Regarding the wishes, I can't simply press the button to initiate a wish, and I can't exchange primogems for intertwined fates.

**Which branch did you use?**

**Screenshots**

![grafik](https://github.com/Grasscutters/Grasscutter/assets/53271427/0a38af98-a24d-4e31-a334-0493fe3ec2a5)

**Additional context**

**Comment by NotThorny** [comment]
Shops do currently have some issues, likely due to proto/resource issues. Cooking can be done as long as you have given yourself recipes first.
Wishing can also be done, but you must already have the wish item. This is also likely due to proto issues where the conversion cannot be done automatically. You need to purchase the fates (or give them to yourself) beforehand.

**Comment by pbz134** [comment]
Hello, purchasing fates does not work either, as the shop is empty as well.
But giving them to me via the chat commands seems to work.

**Comment by Gaobaiawa** [comment]
Manually modify shop.json and place it in the grasscutter/data directory
