### ISSUE TITLE
Hardcoded ENCRYPT_SEED

### ISSUE THREAD

**Issue by Gax-c** [Melledy/Grasscutter#2510]
Hello! I am new to Grasscutter and when I was browsing the code I found the encryption seed is hardcoded in the code [here](https://github.com/Grasscutters/Grasscutter/blob/402226788889fc36da8e9d2d0b856885ea268710/src/main/java/emu/grasscutter/utils/Crypto.java#L22). 
```java
    public static long ENCRYPT_SEED = Long.parseUnsignedLong("11468049314633205968");
```
Using SecureRandom to generate the ENCRYPT_SEED can be a better choice.

**Comment by KingRainbow44** [comment]
hello! not necessarily a bug, but for some clarification:
the encryption seed is hardcoded due to the symmetric key being hardcoded.
to securely generate a seed would require Grasscutter to implement the Mersenne Twister algorithm and generate a key for each player.
as Grasscutter is more of a private server, this encryption isn't super helpful/necessary, and i'd imagine that it was only hardcoded in the first place for simplicity.
