### ISSUE TITLE
The account creation is abnormal

### ISSUE THREAD

**Issue by kamome417** [Melledy/Grasscutter#2523]
The instructions to create an account are:account create <username> <password> [<UID>]，But after using the directive, it becomes：account create <username>[<UID>]
For example：account create 55555 444 1451
<INFO:CommandHandler> An account with UID 444 has been created
how to fix this

**Comment by NotThorny** [comment]
> account create 55555 444 1451

This is not valid usage of the account command. Please refer again to the usage:
`Usage: account create <username> [<UID>]`

So a valid usage would be: `account create myName`
Another valid usage would be `account create myName2 1234`

UID is **optional**, not required, which is why it has brackets. Those indicate an optional input.

**Comment by kamome417** [comment]
thanks
