### ISSUE TITLE
关于角色大招无敌帧的思路

### ISSUE THREAD

**Issue by a267764** [Melledy/Grasscutter#517]
grasscutter的命令中提供了一种无敌代码，需要用到serve的虚拟角色，对话框之后可以获得无敌效果，而角色在开启大招的时候都应当获得这个效果，从而避免角色在释放大招时观看角色动画所导致的角色掉血。
受到这个bug严重的影响的角色，钟离，开启护盾后，在开启e技能，正常状态下不会受到伤害，但使用大招的时候由于丢失无敌帧，会导致开启护盾状态下的钟离受到伤害。对于此处的改善思路，则是提供一个自主的无敌代码，让角色们在开大的时候都自主调用这行代码，做到开大期间的无敌帧

**Comment by Scirese** [comment]
最好用英文说

**Comment by SleepyAsh0191** [comment]
Translate: (Convenient for English user)

Title: Some idea for invincibility frame when press Q


grasscutter provides godmode command, needs "server" virtual character(Console), when console send message, we will enable the godmode, and the character should get this effect when using elemental burst, in order to avoid the character's HP loss caused by watching the character animation when press Q.


Characters severely affected by this bug: ZhongLi, when using elemental skill, his shield appeared, normally does not take damage. But when using the elemental burst, due to the loss of invincibility frames, it will cause Zhongli with shield take damage. For the improvement idea here, it is to provide an independent invincible code, so that the characters can invoke this line of code independently when press Q, so as to make the invincible frame during the elemental burst.



sry 4 my bad English grammar.

**Comment by WetABQ** [comment]
> sscutter的命令中提供了一种无敌代码，需要用到serve的虚拟角色，

这很难为每一个角色的大招时间做精准的分析，我们需要找到 `BintOutput` 有关动画时间的描述（而不是 Hardcode）
这是不是一件简单的事情。

it's hard to implement the invincibility frame for the specific animation duration of each character, we need to find out which configuration has described the animation duration of each character (rather than hardcode them or constant time in code)

find those configurations are NOT as easy as u imagine.

**Comment by mingjun97** [comment]
Tried a lot to find the corresponding field in json file in `ExcelBinOutput` folder but luck is no on my side.

**Comment by hulahupjingga** [comment]
> Translate: (Convenient for English user)
> 
> Title: Some idea for invincibility frame when press Q
> 
> grasscutter provides godmode command, needs "server" virtual character(Console), when console send message, we will enable the godmode, and the character should get this effect when using elemental burst, in order to avoid the character's HP loss caused by watching the character animation when press Q.
> 
> Characters severely affected by this bug: ZhongLi, when using elemental skill, his shield appeared, normally does not take damage. But when using the elemental burst, due to the loss of invincibility frames, it will cause Zhongli with shield take damage. For the improvement idea here, it is to provide an independent invincible code, so that the characters can invoke this line of code independently when press Q, so as to make the invincible frame during the elemental burst.
> 
> sry 4 my bad English grammar.

i wonder why zhongli shield doesn't work properly during elemental burst animation?

**Comment by KingRainbow44** [comment]
The PR stated above will fix this "issue".
