### ISSUE TITLE
There is a problem with the setstats command

### ISSUE THREAD

**Issue by yuexuanblog** [Melledy/Grasscutter#717]
The character status set by this command can only last once

Latest dev branch

For example, setstats ATK 30000, the attack power set by this command can only attack the target once, and then restore the previous attack power level
For example, setstats MHP 30000. After the health value set by this command is restored by using the heal command, the health value will return to the health value level before setting

**Comment by Lynricsy** [comment]
However,if you only attack the monsters you spawned,the effect can last for a long time.Actually,this issue was mentioned many times,but no one fixed it.

**Comment by Birdulon** [comment]
The command sets the stat, it doesn't freeze it.
If you set your HP to 1000 and take damage, your HP won't be 1000 anymore.
If you set your ATK to 1000 and switch weapons, your ATK won't be 1000 anymore.
If you set your max HP to 1000 and switch artifacts, your max HP won't be 1000 anymore.
If you set your cooldown reduction to 100% and get hit by an Abyss Herald's slowing water attack, it won't be 100% anymore.

The issue is some actions in the game trigger a recalculation of stats that you may not expect, for instance attacking enemies can trigger all sorts of events.
