### ISSUE TITLE
深渊打了第8关之后打不了第9关。

### ISSUE THREAD

**Issue by Qingbyue** [Melledy/Grasscutter#719]
深渊打了第8关之后无法进入第9关，并且在双队伍挑战中上半的怪物会重生部分跑到下半，并且生成的怪物的数量不对，会一次生成，之前都是正常，一波一波生成。而且有些时候怪物没打死完就过关了。

**Comment by xmgnew** [comment]
Translate: After beating 8th floor in Spiral Abyss, I am unable to go into 9th floor. The order of monsters spawning are also messed up, they spawn at the same time again (old bug, fixed in previous build but appears again) and some of the monsters even kept to the second half.

Note: I encountered the same issue

**Comment by Akka0** [comment]
> 并且生成的怪物的数量不对，会一次生成，之前都是正常，一波一波生成。而且有些时候怪物没打死完就过关了。

Fixed  #723

> 深渊打了第8关之后无法进入第9关，并且在双队伍挑战中上半的怪物会重生部分跑到下半，

i will fix later.

**Comment by StillMi** [comment]
> > 并且生成的怪物的数量不对，会一次生成，之前都是正常，一波一波生成。而且有些时候怪物没打死完就过关了。
> 
> Fixed #723
> 
> > 深渊打了第8关之后无法进入第9关，并且在双队伍挑战中上半的怪物会重生部分跑到下半，
> 
> i will fix later.

Monsters on the second level of the Ninth level will refresh indefinitely and get stuck

**Comment by JrantKing** [comment]
6-3 the second half could not be completed normally

> > 并且生成的怪物的数量不对，会一次生成，之前都是正常，一波一波生成。而且有些时候怪物没打死完就过关了。
> 
> Fixed #723
> 
> > 深渊打了第8关之后无法进入第9关，并且在双队伍挑战中上半的怪物会重生部分跑到下半，
> 
> i will fix later.

**Comment by lunaticwhat** [comment]
duplcated issue with #698 since abyss wasnt properly implemented yet.
