### ISSUE TITLE
[Issue] the connect is timeout

### ISSUE THREAD

**Issue by Xsj123452** [Melledy/Grasscutter#739]
![image](https://user-images.githubusercontent.com/57057886/167440655-9cef9c07-2d2e-4a72-9813-bf458d1b48f7.png)

how to slove

**Comment by lunaticwhat** [comment]
which kind of server you running on, local or dedicated ?

**Comment by KennanChan** [comment]
It is mostly caused by not able to establish a UDP connection to the game server.
I ran into this issue these days. The client connects to the server well within my home physical network. When I shift to cellular network and connect my phone to my home network using IPSec VPN provided by my openwrt router, I can access the local network server but the udp connection somehow cannot be established correctly which results in the timeout issue.
I now solve the problem by changing the VPN server from IPSec(IKEv1) to L2TP provided by Softether VPN(hosted in a docker container). Anyone with similar network configuration can give a try.

**Comment by memetrollsXD** [comment]
**This is an issue tracker, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.**

GitHub issue 不是技术支持论坛。需要技术支持请去 [Discord](https://discord.gg/T5vZU6UyeG)，里面有专门的中文频道

**Comment by EssDeath** [comment]
hey man . can you help me . i have  the same issue . how can i change VPN server from IPSec(IKEv1) to L2TP ? this time outs are so bad ...

**Comment by KennanChan** [comment]
I created a docker container to run Softether VPN which provides L2TP over IPSec VPN. I am using openwrt router with docker ce installed.
