### ISSUE TITLE
 Build #855 - 4206 error, query_cur_region not found

### ISSUE THREAD

**Issue by Ljzd-PRO** [Melledy/Grasscutter#941]
**Describe the bug**

Build #855 crashed, I entered `https://host/query_cur_region`, and met 404 Not Found error, when entering game server, I met 4206 error.
After I moved  `query_cur_region.txt` and `query_region_list.txt` from stable branch to my folder, it still not work.
I used my domain certificate to set for keystore file and connect from WAN. There was no error in mitmproxy logs.

**Which branch did you use?**

development Build #855

**Comment by misaka10843** [comment]
Are you sure the configuration file is up to date?
This may be because the configuration file has changed in recent versions, so it needs to be reconfigured.

**Comment by Ljzd-PRO** [comment]
> Are you sure the configuration file is up to date?
> This may be because the configuration file has changed in recent versions, so it needs to be reconfigured.

The configuration file was generated by the jar file that GitHub Action build.

**Comment by misaka10843** [comment]
> 
Then if you are deploying in a server, try to see if these two places are filled in correctly (accessAddress and accessPort)
If you are deployed in the client, it may be due to a certificate problem (but the chances are slim)

![图片](https://user-images.githubusercontent.com/69132853/168602548-520e8a7c-f84b-4c97-9666-19c8c17116ad.png)
![图片](https://user-images.githubusercontent.com/69132853/168602603-2335efc0-2558-4ea3-936d-a548870f388f.png)

**Comment by KingRainbow44** [comment]
`query_cur_region` is no longer a valid endpoint. you must use `query_cur_region/os_usa` or similar

**Comment by SwirlClinic** [comment]
Problem with that is when ios attempts to make a request it will look like this:
https://somerandomdomain.com/query_cur_region?version=OSRELiOS2.6.0&lang=1&platform=1&binary=1&time=39&channel_id=1&sub_channel_id=0&account_type=1&dispatchSeed=f3f32cfe536436b2

This causes it to 4206
